apiVersion: v1
kind: Service
metadata:
  name: artifactory-oss
  labels:
    app: artifactory-oss
    component: service
  annotations:
    description: 'Exposes the artifactory-oss server'
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: artifactory-oss
    component: artifactory-oss-server
